In [1]:
# a_verify_install.py

import torch

# 打印PyTorch版本
print(f"PyTorch Version: {torch.__version__}")

# 检查GPU是否可用
is_cuda_available = torch.cuda.is_available()
print(f"CUDA (GPU) Available: {is_cuda_available}")

if is_cuda_available:
    # 打印GPU数量
    print(f"Number of GPUs: {torch.cuda.device_count()}")
    # 打印当前GPU设备名称
    print(f"Current GPU Name: {torch.cuda.get_device_name(0)}")


PyTorch Version: 2.8.0+cu126
CUDA (GPU) Available: True
Number of GPUs: 1
Current GPU Name: Tesla T4


In [2]:
# b_tensors_demo.py

import torch
import numpy as np

# 1. 创建Tensor
# 从列表创建
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor from list:\n {x_data}\n")

# 从NumPy数组创建 (共享内存)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor from NumPy:\n {x_np}\n")

# 创建指定形状的全1或随机Tensor
shape = (2, 3,)
ones_tensor = torch.ones(shape)
rand_tensor = torch.rand(shape)
print(f"Ones Tensor:\n {ones_tensor}\n")
print(f"Random Tensor:\n {rand_tensor}\n")

# 2. Tensor的属性
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}\n")

# 3. Tensor操作 (类似NumPy)
# 索引和切片
tensor = torch.ones(4, 4)
tensor[:, 1] = 0 # 将第二列全部置为0
print(f"Sliced Tensor:\n {tensor}\n")

# 矩阵乘法
mat_mul = tensor.matmul(tensor.T) # .T 是转置
print(f"Matrix Multiplication:\n {mat_mul}\n")

# 元素级乘法
elem_mul = tensor.mul(tensor)
# 或者 torch.mul(tensor, tensor)
print(f"Element-wise Multiplication:\n {elem_mul}\n")

# Tensor与标量的运算
added_tensor = tensor.add(5)
print(f"Tensor after adding 5:\n {added_tensor}\n")


Tensor from list:
 tensor([[1, 2],
        [3, 4]])

Tensor from NumPy:
 tensor([[1, 2],
        [3, 4]])

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random Tensor:
 tensor([[0.1106, 0.5699, 0.5976],
        [0.3549, 0.4626, 0.0076]])

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu

Sliced Tensor:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Matrix Multiplication:
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

Element-wise Multiplication:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Tensor after adding 5:
 tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])



In [3]:
# c_autograd_demo.py

import torch

# 创建一个需要梯度的Tensor，这是模型参数的模拟
# requires_grad=True 告诉PyTorch需要追踪对该Tensor的所有操作
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

# 定义一个简单的线性模型
x = torch.tensor(3.0)
y = w * x + b  # y = 2*3 + 1 = 7

# 假设我们有一个目标值
target = torch.tensor(10.0)

# 计算损失 (这里用简单的平方差)
loss = (target - y)**2 # loss = (10 - 7)^2 = 9

# 执行反向传播，计算梯度
# loss是一个标量，所以可以直接调用.backward()
loss.backward()

# 打印梯度
# d(loss)/dw = d((10 - (w*x+b))^2)/dw = 2 * (10 - (w*x+b)) * (-x) = 2 * 3 * (-3) = -18
print(f"Gradient of w (dw): {w.grad}")

# d(loss)/db = d((10 - (w*x+b))^2)/db = 2 * (10 - (w*x+b)) * (-1) = 2 * 3 * (-1) = -6
print(f"Gradient of b (db): {b.grad}")


Gradient of w (dw): -18.0
Gradient of b (db): -6.0


In [4]:
# d_nn_module_demo.py

import torch
from torch import nn

# 定义一个简单的全连接神经网络
class SimpleNet(nn.Module):
    def __init__(self):
        # 必须先调用父类的__init__方法
        super().__init__()

        # 定义网络的层次结构
        # nn.Linear(input_features, output_features) 定义一个全连接层
        self.layer1 = nn.Linear(10, 32) # 输入10个特征，输出32个特征
        self.activation1 = nn.ReLU()   # ReLU激活函数
        self.layer2 = nn.Linear(32, 1) # 输入32个特征，输出1个特征 (例如，回归任务)

    def forward(self, x):
        # 定义数据的前向传播路径
        x = self.layer1(x)
        x = self.activation1(x)
        x = self.layer2(x)
        return x

# 实例化模型
model = SimpleNet()
print(model)

# 创建一个假的输入数据 (batch_size=5, features=10)
dummy_input = torch.randn(5, 10)

# 将数据传入模型，得到输出
output = model(dummy_input)

print(f"\nInput shape: {dummy_input.shape}")
print(f"Output shape: {output.shape}")


SimpleNet(
  (layer1): Linear(in_features=10, out_features=32, bias=True)
  (activation1): ReLU()
  (layer2): Linear(in_features=32, out_features=1, bias=True)
)

Input shape: torch.Size([5, 10])
Output shape: torch.Size([5, 1])


In [5]:
# 在Colab单元格中运行

import torch
from torch import nn

# 定义一个更结构化的神经网络
class RegressionNet(nn.Module):
    def __init__(self):
        super().__init__()

        # 定义网络的输入、隐藏和输出层的维度
        input_features = 10  # 假设我们的数据有10个特征
        hidden_units_1 = 64
        hidden_units_2 = 32
        output_features = 1   # 回归任务，输出1个值

        # 使用 nn.Sequential 将网络层串联起来
        # 这是一个清晰、模块化的方式来定义模型
        self.layers = nn.Sequential(
            nn.Linear(input_features, hidden_units_1),
            nn.ReLU(),  # 激活函数，引入非线性
            nn.Linear(hidden_units_1, hidden_units_2),
            nn.ReLU(),
            nn.Linear(hidden_units_2, output_features)
        )

    def forward(self, x):
        # 由于使用了nn.Sequential，forward函数变得极其简单
        return self.layers(x)

# 实例化模型
model = RegressionNet()
print("模型结构:")
print(model)

# 创建一个假的输入数据 (batch_size=5, features=10)
dummy_input = torch.randn(5, 10)

# 将数据传入模型，得到输出
output = model(dummy_input)

print(f"\n输入形状: {dummy_input.shape}")
print(f"输出形状: {output.shape}")


模型结构:
RegressionNet(
  (layers): Sequential(
    (0): Linear(in_features=10, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=32, bias=True)
    (3): ReLU()
    (4): Linear(in_features=32, out_features=1, bias=True)
  )
)

输入形状: torch.Size([5, 10])
输出形状: torch.Size([5, 1])


In [6]:
# 在Colab单元格中运行

# 实例化我们在Step 4中定义的模型
model = RegressionNet()

# 1. 定义损失函数
# Mean Squared Error Loss，适用于回归问题
loss_fn = nn.MSELoss()

# 2. 定义优化器
# Adam优化器是一种非常流行的选择
# 第一个参数 model.parameters() 告诉优化器需要更新哪些参数
# lr (learning_rate) 是学习率，控制每次参数更新的步长
optimizer = torch.optim.Adam(params=model.parameters(), lr=0.001)

print(f"损失函数: {loss_fn}")
print(f"优化器: {optimizer}")


损失函数: MSELoss()
优化器: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)


In [7]:
# 在Colab单元格中运行

from torch.utils.data import TensorDataset, DataLoader

# 1. 创建合成数据
# 假设我们有1000个样本，每个样本有10个特征
num_samples = 1000
num_features = 10

# X 是我们的特征 (随机生成)
X = torch.randn(num_samples, num_features)

# y 是我们的目标值 (假设是一个简单的线性关系加上一些噪声)
true_weights = torch.tensor([0.5, -0.2, 1.5, -2.0, 0.8, -1.1, 0.3, -0.7, 1.2, -0.9])
true_bias = 2.0
y = X @ true_weights + true_bias + torch.randn(num_samples) * 0.1 # 矩阵乘法 + 偏置 + 噪声
# y需要和模型输出的形状匹配，这里模型输出是(batch_size, 1)，所以我们reshape一下
y = y.view(-1, 1)

print(f"特征数据形状: {X.shape}")
print(f"标签数据形状: {y.shape}\n")

# 2. 创建Dataset
# TensorDataset将我们的特征和标签张量打包在一起
dataset = TensorDataset(X, y)

# 3. 创建DataLoader
# BATCH_SIZE 决定了每次训练模型时使用多少个数据样本
BATCH_SIZE = 32

# shuffle=True 在每个epoch开始时都会打乱数据顺序，这对于训练非常重要
# 它可以防止模型学到数据的特定顺序
data_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

# 我们可以检查一下DataLoader的工作方式
# 从data_loader中取出一个批次的数据
features_batch, labels_batch = next(iter(data_loader))
print(f"从DataLoader取出的一个批次:")
print(f"  特征批次形状: {features_batch.shape}")
print(f"  标签批次形状: {labels_batch.shape}")


特征数据形状: torch.Size([1000, 10])
标签数据形状: torch.Size([1000, 1])

从DataLoader取出的一个批次:
  特征批次形状: torch.Size([32, 10])
  标签批次形状: torch.Size([32, 1])


In [8]:
# 在Colab单元格中运行

# --- 准备工作 (从前面步骤复制代码) ---
# 1. 模型
model = RegressionNet()
# 2. 损失函数
loss_fn = nn.MSELoss()
# 3. 优化器
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
# 4. 数据加载器 (假设dataset和data_loader已在上一单元格创建)
# data_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

# --- 训练循环 ---
# epochs 是我们希望在整个数据集上训练的总轮数
epochs = 10

print("开始训练...")

# 外层循环遍历每一轮
for epoch in range(epochs):
    # 将模型设置为训练模式
    model.train()

    # 内层循环遍历DataLoader中的每一个批次
    for batch, (X_batch, y_batch) in enumerate(data_loader):

        # 1. 前向传播：计算预测值
        y_pred = model(X_batch)

        # 2. 计算损失
        loss = loss_fn(y_pred, y_batch)

        # 3. 优化器三步舞
        # 3.1 清空梯度
        optimizer.zero_grad()
        # 3.2 反向传播：计算梯度
        loss.backward()
        # 3.3 更新权重
        optimizer.step()

    # 在每轮训练结束后，打印损失信息
    # 我们可以在评估模式下计算损失，这会关闭Dropout等层，但对于这个简单模型影响不大
    model.eval()
    with torch.no_grad(): # 在这个块中，不计算梯度，节省计算资源
        y_pred_total = model(X) # 在整个数据集上进行预测
        epoch_loss = loss_fn(y_pred_total, y)
        print(f"Epoch {epoch+1}/{epochs} | Loss: {epoch_loss.item():.4f}")

print("\n训练完成！")


开始训练...
Epoch 1/10 | Loss: 11.4291
Epoch 2/10 | Loss: 6.1704
Epoch 3/10 | Loss: 1.6792
Epoch 4/10 | Loss: 0.4714
Epoch 5/10 | Loss: 0.3110
Epoch 6/10 | Loss: 0.2277
Epoch 7/10 | Loss: 0.1758
Epoch 8/10 | Loss: 0.1404
Epoch 9/10 | Loss: 0.1126
Epoch 10/10 | Loss: 0.0945

训练完成！


In [9]:
# 在Colab单元格中运行

# 1. 设置设备
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"正在使用的设备: {device}\n")

# --- 准备工作 (GPU版本) ---
# 1. 模型
model_gpu = RegressionNet().to(device) # 将模型移动到GPU

# 2. 损失函数 (损失函数通常不需要移动)
loss_fn = nn.MSELoss()

# 3. 优化器 (优化器会自动处理参数所在的设备)
optimizer = torch.optim.Adam(model_gpu.parameters(), lr=0.001)

# 4. 数据 (对于大型数据集，在训练循环中移动数据批次是最高效的)
# X_gpu = X.to(device)
# y_gpu = y.to(device)
# dataset_gpu = TensorDataset(X_gpu, y_gpu)
# data_loader_gpu = DataLoader(dataset_gpu, batch_size=BATCH_SIZE, shuffle=True)

# --- 训练循环 (GPU版本) ---
epochs = 10
print("开始在GPU上训练...")

for epoch in range(epochs):
    model_gpu.train()
    for X_batch, y_batch in data_loader:
        # !! 关键步骤: 将数据批次移动到GPU !!
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)

        y_pred = model_gpu(X_batch)
        loss = loss_fn(y_pred, y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    # 打印损失
    model_gpu.eval()
    with torch.no_grad():
        # 将整个数据集移动到GPU进行评估
        epoch_loss = loss_fn(model_gpu(X.to(device)), y.to(device))
        print(f"Epoch {epoch+1}/{epochs} | Loss: {epoch_loss.item():.4f}")

print("\n训练完成！")


# --- 5. 保存和加载模型 ---

# 定义模型保存路径
MODEL_PATH = "regression_model.pth"

# 保存模型的状态字典
print(f"\n正在保存模型到: {MODEL_PATH}")
torch.save(obj=model_gpu.state_dict(), f=MODEL_PATH)

# 加载模型
# 1. 创建一个新的、未经训练的模型实例
loaded_model = RegressionNet()

# 2. 加载已保存的状态字典
# 注意：加载前，模型需要知道参数应该在哪个设备上
# 我们先加载到CPU，然后再移动到目标设备
loaded_model.load_state_dict(torch.load(f=MODEL_PATH))

# 3. 将加载的模型移动到目标设备
loaded_model.to(device)

# 4. 测试加载的模型
loaded_model.eval()
with torch.no_grad():
    # 使用加载的模型进行预测
    sample_input = torch.randn(1, 10).to(device)
    prediction = loaded_model(sample_input)
    print(f"\n使用加载的模型进行预测:")
    print(f"输入: {sample_input.cpu().numpy()}")
    print(f"预测输出: {prediction.cpu().numpy()}")


正在使用的设备: cuda

开始在GPU上训练...
Epoch 1/10 | Loss: 12.5242
Epoch 2/10 | Loss: 6.5093
Epoch 3/10 | Loss: 1.1389
Epoch 4/10 | Loss: 0.2795
Epoch 5/10 | Loss: 0.1995
Epoch 6/10 | Loss: 0.1511
Epoch 7/10 | Loss: 0.1188
Epoch 8/10 | Loss: 0.0986
Epoch 9/10 | Loss: 0.0820
Epoch 10/10 | Loss: 0.0687

训练完成！

正在保存模型到: regression_model.pth

使用加载的模型进行预测:
输入: [[-0.10295513  0.4530604  -1.9070609   0.12943898 -0.07786548 -0.5137562
   1.0706341  -0.99571174  0.15195853 -0.9119981 ]]
预测输出: [[1.3044779]]


In [10]:
# 在Colab单元格中运行

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, models, transforms
import os
import zipfile
from tqdm import tqdm # 用于显示漂亮的进度条

# 1. 下载数据集
# a wget command to download the dataset
!wget https://download.pytorch.org/tutorial/hymenoptera_data.zip

# 2. 解压数据集
with zipfile.ZipFile("hymenoptera_data.zip", 'r') as zip_ref:
    zip_ref.extractall(".")

# 3. 定义数据路径
data_dir = "hymenoptera_data"
train_dir = os.path.join(data_dir, "train")
val_dir = os.path.join(data_dir, "val")

print(f"训练数据目录: {train_dir}")
print(f"验证数据目录: {val_dir}")
# 你可以看到目录下已经分好了 'ants' 和 'bees' 两个文件夹
print(f"训练集中的类别: {os.listdir(train_dir)}")


--2025-09-09 15:33:33--  https://download.pytorch.org/tutorial/hymenoptera_data.zip
Resolving download.pytorch.org (download.pytorch.org)... 99.84.215.85, 99.84.215.59, 99.84.215.76, ...
Connecting to download.pytorch.org (download.pytorch.org)|99.84.215.85|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47286322 (45M) [application/zip]
Saving to: ‘hymenoptera_data.zip’

hymenoptera_data.zi 100%[===================>]  45.10M   226MB/s    in 0.2s    

2025-09-09 15:33:33 (226 MB/s) - ‘hymenoptera_data.zip’ saved [47286322/47286322]

训练数据目录: hymenoptera_data/train
验证数据目录: hymenoptera_data/val
训练集中的类别: ['bees', 'ants']


In [11]:
# 在Colab单元格中运行

# 1. 定义数据预处理和增强
# 对训练集和验证集使用不同的变换
data_transforms = {
    'train': transforms.Compose([
        transforms.RandomResizedCrop(224), # 随机裁剪到224x224
        transforms.RandomHorizontalFlip(), # 随机水平翻转
        transforms.ToTensor(), # 转换为Tensor
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]) # 标准化
    ]),
    'val': transforms.Compose([
        transforms.Resize(256), # 缩放到256
        transforms.CenterCrop(224), # 中心裁剪到224x224
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

# 2. 使用 ImageFolder 创建 Datasets
# ImageFolder 是一个神奇的工具，它会自动从文件夹结构中读取图片和标签
image_datasets = {x: datasets.ImageFolder(os.path.join(data_dir, x), data_transforms[x])
                  for x in ['train', 'val']}

# 3. 创建 DataLoaders
dataloaders = {x: DataLoader(image_datasets[x], batch_size=4, shuffle=True, num_workers=2)
               for x in ['train', 'val']}

# 4. 获取数据集大小和类别名称
dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'val']}
class_names = image_datasets['train'].classes

print(f"数据集大小: {dataset_sizes}")
print(f"类别: {class_names}")


数据集大小: {'train': 244, 'val': 153}
类别: ['ants', 'bees']


In [12]:
# 在Colab单元格中运行

# 1. 加载预训练的ResNet-18模型
# weights=models.ResNet18_Weights.DEFAULT 是当前推荐的加载最新预训练权重的方法
model_ft = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)

# 2. 冻结所有基础层参数
# 我们不希望在初始训练时破坏预训练模型已经学到的特征
for param in model_ft.parameters():
    param.requires_grad = False

# 3. 修改分类器 (最后一层)
# ResNet-18的最后一层是一个名为 `fc` 的全连接层
num_ftrs = model_ft.fc.in_features # 获取原始最后一层的输入特征数
# 将其替换为一个新的全连接层，输出我们需要的类别数 (蚂蚁 vs 蜜蜂 -> 2)
# 注意：新创建的层的参数默认 requires_grad=True
model_ft.fc = nn.Linear(num_ftrs, len(class_names))

# 4. 将模型移动到GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
model_ft = model_ft.to(device)

print("修改后的模型结构 (只看最后几层):")
print(model_ft)

# 5. 定义损失函数和优化器
criterion = nn.CrossEntropyLoss()
# 只优化我们修改过的分类器层的参数
optimizer_ft = optim.SGD(model_ft.fc.parameters(), lr=0.001, momentum=0.9)


Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


100%|██████████| 44.7M/44.7M [00:00<00:00, 179MB/s]


修改后的模型结构 (只看最后几层):
ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): Re

In [13]:
# 在Colab单元格中运行

# --- 训练循环 ---
epochs = 15
print("\n开始微调训练...")

for epoch in range(epochs):
    print(f'Epoch {epoch+1}/{epochs}')
    print('-' * 10)

    # 每个epoch都有一个训练和验证阶段
    for phase in ['train', 'val']:
        if phase == 'train':
            model_ft.train()  # 设置模型为训练模式
        else:
            model_ft.eval()   # 设置模型为评估模式

        running_loss = 0.0
        running_corrects = 0

        # 迭代数据
        for inputs, labels in tqdm(dataloaders[phase], desc=phase):
            inputs = inputs.to(device)
            labels = labels.to(device)

            # 梯度清零
            optimizer_ft.zero_grad()

            # 只在训练阶段进行前向传播和反向传播
            with torch.set_grad_enabled(phase == 'train'):
                outputs = model_ft(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)

                # 如果是训练阶段，则执行反向传播 + 优化
                if phase == 'train':
                    loss.backward()
                    optimizer_ft.step()

            # 统计损失和准确率
            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)

        epoch_loss = running_loss / dataset_sizes[phase]
        epoch_acc = running_corrects.double() / dataset_sizes[phase]

        print(f'{phase} Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}\n')

print("微调完成！")



开始微调训练...
Epoch 1/15
----------


train: 100%|██████████| 61/61 [00:03<00:00, 17.55it/s]


train Loss: 1.2662 Acc: 0.5656



val: 100%|██████████| 39/39 [00:00<00:00, 39.06it/s]


val Loss: 0.7826 Acc: 0.6536

Epoch 2/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 49.77it/s]


train Loss: 0.5989 Acc: 0.7459



val: 100%|██████████| 39/39 [00:01<00:00, 36.79it/s]


val Loss: 0.2087 Acc: 0.9346

Epoch 3/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 49.27it/s]


train Loss: 0.4905 Acc: 0.8279



val: 100%|██████████| 39/39 [00:00<00:00, 39.44it/s]


val Loss: 0.2472 Acc: 0.9020

Epoch 4/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 38.10it/s]


train Loss: 0.6104 Acc: 0.7582



val: 100%|██████████| 39/39 [00:01<00:00, 24.62it/s]


val Loss: 0.2143 Acc: 0.9412

Epoch 5/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 47.75it/s]


train Loss: 0.4771 Acc: 0.8156



val: 100%|██████████| 39/39 [00:00<00:00, 39.28it/s]


val Loss: 0.1588 Acc: 0.9608

Epoch 6/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 48.13it/s]


train Loss: 0.5050 Acc: 0.7910



val: 100%|██████████| 39/39 [00:00<00:00, 39.39it/s]


val Loss: 0.1954 Acc: 0.9346

Epoch 7/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 48.32it/s]


train Loss: 0.3936 Acc: 0.8156



val: 100%|██████████| 39/39 [00:00<00:00, 39.36it/s]


val Loss: 0.2443 Acc: 0.9085

Epoch 8/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 49.13it/s]


train Loss: 0.4492 Acc: 0.8156



val: 100%|██████████| 39/39 [00:00<00:00, 40.74it/s]


val Loss: 0.1605 Acc: 0.9608

Epoch 9/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 44.66it/s]


train Loss: 0.4061 Acc: 0.8443



val: 100%|██████████| 39/39 [00:01<00:00, 20.10it/s]


val Loss: 0.1804 Acc: 0.9346

Epoch 10/15
----------


train: 100%|██████████| 61/61 [00:02<00:00, 26.16it/s]


train Loss: 0.5158 Acc: 0.7910



val: 100%|██████████| 39/39 [00:01<00:00, 38.87it/s]


val Loss: 0.4425 Acc: 0.8366

Epoch 11/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 48.90it/s]


train Loss: 0.6047 Acc: 0.7459



val: 100%|██████████| 39/39 [00:00<00:00, 39.87it/s]


val Loss: 0.3410 Acc: 0.8824

Epoch 12/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 48.51it/s]


train Loss: 0.5398 Acc: 0.7746



val: 100%|██████████| 39/39 [00:00<00:00, 40.35it/s]


val Loss: 0.4665 Acc: 0.8431

Epoch 13/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 49.96it/s]


train Loss: 0.5728 Acc: 0.7869



val: 100%|██████████| 39/39 [00:00<00:00, 39.74it/s]


val Loss: 0.3333 Acc: 0.8954

Epoch 14/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 32.38it/s]


train Loss: 0.5246 Acc: 0.8156



val: 100%|██████████| 39/39 [00:01<00:00, 26.94it/s]


val Loss: 0.2527 Acc: 0.9346

Epoch 15/15
----------


train: 100%|██████████| 61/61 [00:01<00:00, 48.99it/s]


train Loss: 0.3857 Acc: 0.8279



val: 100%|██████████| 39/39 [00:01<00:00, 38.76it/s]

val Loss: 0.2431 Acc: 0.9281

微调完成！
